name: Flint Ghost Sync
on:
  repository_dispatch:
    types: [admin_sync]

jobs:
  sync-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Sync Script
        env:
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: python sync_flint.py

      - name: Commit and Push
        run: |
          git config --global user.name "Flint-Bot"
          git config --global user.email "bot@flint.dev"
          # Now pointing specifically to the data folder
          git add data/games.json data/apps.json data/quotes.json
          git commit -m "Automated Update "
          git push
